---
Name: approutes
After:
  - "#rootroutes"
  - "#coreroutes"
---
SilverStripe\Control\Director:
  rules:
    "Auth//$Action/$ID": AuthController
    "Dashboard//$Action/$ID": DashboardController
    "Product//$Action/$ID": ProductController
    "Warna//$Action/$ID": WarnaController
